### PR TITLE
Rename TizenExtension with DartPluginRegistry

### PR DESCRIPTION
**Pull request by swift-kim**
Also a few minor changes (see the commit log).

### CODE REVIEW

**Review by HakkyuKim — APPROVED** [review]

**Comment by HakkyuKim** [comment]
Oh, I overlooked having to set default values for `TestWrapper` and `FlutterTestRunner`. Currently they're explicitly set to null in `super()`.

**Comment by swift-kim** [comment]
@HakkyuKim They are initialized to default instances if not set.

**Comment by HakkyuKim** [comment]
@swift-kim This is the output when running `flutter-tizen test`
```
NoSuchMethodError: The method 'runTests' was called on null.
Receiver: null
Tried calling: runTests(null, Instance(length:1) of '_GrowableList', buildTestAssets: true, concurrency: 10, debuggingOptions: Instance of 'DebuggingOptions', enableObservatory: false, excludeTags: null, flutterProject: Instance of 'FlutterProject', integrationTestDevice: null, integrationTestUserIdentifier: null, ipv6: false, machine: false, names: Instance(length:0) of '_GrowableList', plainNames: Instance(length:0) of '_GrowableList', randomSeed: null, reporter: "compact", runSkipped: false, shardIndex: null, tags: null, timeout: "30s", totalShards: null, updateGoldens: false, watcher: null, web: false)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:430:41)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
<asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     main (package:flutter_tizen/executable.dart:82:3)
<asynchronous suspension>

```

**Comment by swift-kim** [comment]
@HakkyuKim You're right. I'll just revert the change.

**Comment by HakkyuKim** [comment]
@swift-kim Okay, LGTM again.

**Pull request merged**
