### PR TITLE
Fix reading of collection size

### PR DESCRIPTION
**Pull request by lenchis001**

### CODE REVIEW

**Comment by WonyoungChoi** [comment]
Thanks for finding a bug. Please fix `WriteSize()` method together. 
https://github.com/flutter-tizen/flutter-tizen/blob/dd9aca60df98eed60a410a1eec650c56e67c0bb8/embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMessageHelper.cs#L66

**Comment by lenchis001** [comment]
> Thanks for finding a bug. Please fix `WriteSize()` method together.
> 
> https://github.com/flutter-tizen/flutter-tizen/blob/dd9aca60df98eed60a410a1eec650c56e67c0bb8/embedding/csharp/Tizen.Flutter.Embedding/Channels/StandardMessageHelper.cs#L66

Thank you for highlighting this.
Done.

**Comment by lenchis001** [comment]
@WonyoungChoi @swift-kim Could you please merge these changes if it's okay for you?

**Review by swift-kim — APPROVED** [review]
Thank you!

**Pull request merged**
