### PR TITLE
Allow dlogs to return after observatory discovery

### PR DESCRIPTION
**Pull request by HakkyuKim**
Contributes to #168 

Allow dlogs to show in `drive` command.

~~Different solution for https://github.com/flutter/flutter/blob/2dc11a85ff26b434bf0dd391097514b005289681/packages/flutter_tools/lib/src/android/android_device.dart#L602-L604. Applying the same solution causes the following error which I can't figure out, so I'm referencing the [iOS logger logic](https://github.com/flutter/flutter/blob/2dc11a85ff26b434bf0dd391097514b005289681/packages/flutter_tools/lib/src/ios/devices.dart#L732-L748).~~

```
           /tmp/flutter_tools.VYGBSB/CQKUOL/org.tizen.package_info_plus_tizen_example.rpm   1KB/s (60 bytes in 0.037s)
[        ] executing: /home/hakkyu/tizen-studio/tools/sdb -s emulator-26101 shell app_launcher -s org.tizen.package_info_plus_tizen_example
[ +304 ms] ... successfully launched pid = 7058 with debug 0
[        ] Waiting for observatory port to be available...
[   +4 ms] Observatory URL on device: http://127.0.0.1:34138/0ikvTwz3kNk=/
[   +5 ms] executing: /home/hakkyu/tizen-studio/tools/sdb -s emulator-26101 forward tcp:43857 tcp:34138
[   +6 ms] Forwarded host port 43857 to device port 34138 for Observatory
[  +13 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:43857/0ikvTwz3kNk=/.
[  +80 ms] Warning: Failed to start DDS: WebSocketChannelException: WebSocketChannelException: HttpException: Connection closed before full header was
received, uri = http://127.0.0.1:43857/0ikvTwz3kNk=/ws
[   +7 ms] "flutter drive" took 40,636ms.

HttpException: , uri = http://127.0.0.1:43857/0ikvTwz3kNk=/ws
```
## Update

Applied https://github.com/flutter/flutter/blob/2dc11a85ff26b434bf0dd391097514b005289681/packages/flutter_tools/lib/src/android/android_device.dart#L602-L604.

### CODE REVIEW

**Comment by swift-kim** [comment]
> Applying the same solution causes the following error which I can't figure out

Did you forget to set the value for the argument `after` when calling `createLogReader()`? Otherwise the log lines will look like

```
$ sdb dlog ConsoleMessage | ack "Observatory listening on"
I/ConsoleMessage(24835): flutter: Observatory listening on http://127.0.0.1:43213/brEeZSdQvqQ=/
I/ConsoleMessage(25412): flutter: Observatory listening on http://127.0.0.1:46375/Tmq5ig18yq8=/
I/ConsoleMessage(26078): flutter: Observatory listening on http://127.0.0.1:33780/SXApv2kRFPo=/
I/ConsoleMessage(26794): flutter: Observatory listening on http://127.0.0.1:38251/hRvA2KeK9Zo=/
I/ConsoleMessage(27431): flutter: Observatory listening on http://127.0.0.1:41362/2i8zMbnTdIQ=/
```

after multiple debug launches and therefore the observatory will connect to a wrong URL. I think it would be better to add `@required` to the argument to avoid any confusion.

**Comment by HakkyuKim** [comment]
> Did you forget to set the value for the argument after when calling createLogReader()?

Oh wow, that was it! Thank you.

**Review by swift-kim — APPROVED** [review]

**Comment by bbrto21** [comment]
I got below errors with this patch
```bash
boram@boram-ubuntu ~/Work/f-project/flutter-tizen (pr/173) $ sdb dlog -c; sdb dlog ConsoleMessage
I/ConsoleMessage(21024): FlutterApplication.cs: ParseEngineArgs(127) > Enabled: --enable-dart-profiling
I/ConsoleMessage(21024): FlutterApplication.cs: ParseEngineArgs(127) > Enabled: --enable-checked-mode
I/ConsoleMessage(21024): FlutterApplication.cs: ParseEngineArgs(127) > Enabled: --start-paused
I/ConsoleMessage(21024): flutter: Observatory listening on http://127.0.0.1:37473/jwsEtCy_kmU=/
E/ConsoleMessage(21024): Invalid UTF8 sequence encountered, 
E/ConsoleMessage(21024): (Error Code: BA + idx: 2 )(Error Code: AE + idx: 3 )(Error Code: 15 + idx: 4 )
E/ConsoleMessage(21024): [ERROR:flutter/shell/common/shell.cc(103)] Dart Unhandled Exception: Invalid argument(s): Dart_GetField expects argument 'name' to be non-null., stack trace: null
E/ConsoleMessage(21024): [ERROR:flutter/runtime/dart_isolate.cc(713)] Could not resolve main entrypoint function.
E/ConsoleMessage(21024): [ERROR:flutter/runtime/dart_isolate.cc(192)] Could not run the run main Dart entrypoint.
E/ConsoleMessage(21024): [ERROR:flutter/runtime/runtime_controller.cc(415)] Could not create root isolate.
E/ConsoleMessage(21024): [ERROR:flutter/shell/common/shell.cc(588)] Could not launch engine with configuration.
```
```bash
boram@boram-ubuntu ~/Work/f-project/plugins/packages/device_info/example $ flutter-tizen drive --driver=test_driver/integration_test.dart --target=integration_test/device_info_test.dart
Running "flutter pub get" in example...                            643ms
BuilThe platform profile is used for signing.                               
Building a Tizen application in debug mode...                      28.2s
✓ Built build/tizen/tpk/org.tizen.device_info_tizen_example-1.0.0.tpk (24.9MB).
Installing build/tizen/tpk/org.tizen.device_info_tizen_example-1.0.0.tpk...        23.7s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:46529/f8gww_JeaZM=/
VMServiceFlutterDriver: The root isolate is taking an unuusally long time to start.
```

**Comment by swift-kim** [comment]
@bbrto21 Related to https://github.com/flutter-tizen/flutter-tizen/pull/171?

**Comment by bbrto21** [comment]
> @bbrto21 Related to #171?

Should I get this patch on PR #171?

**Review by bbrto21 — APPROVED** [review]
LGTM

**Pull request merged**
