### PR TITLE
Fix engine arugments passing on TV devices

### PR DESCRIPTION
**Pull request by swift-kim**
- Rename `TizenBuildInfo.profile` to `TizenBuildInfo.securityProfile` for clarity
- Do not use `__DLP_UNIT_TEST_ARG__` to pass engine arguments to an app any more. Instead, the tool writes the arguments to a plain text file `/home/owner/share/tmp/sdk_tools/{packageId}.rpm` before launching an app and the app reads it on launch (and deletes). This is the only workaround that works for any device type including secure protocol devices. I tried to make the file automatically expire after some time period (10 seconds) but failed after all. No side effect or problem has been found so far.
- Increase the embedding nuget version to 1.1.0
- Add Tizen 4.0 support to the app template
  - Change the API version to 4.0
  - Change the target framework moniker to tizen40
  - Change the C# API version to 4

### CODE REVIEW

**Comment by bbrto21** [comment]
Does it work on TV emulator too?

**Comment by swift-kim** [comment]
@bbrto21 Sure. I only tested on TV emulator and watches. Needs testing on real TV devices running release images.

**Review by bbrto21 — APPROVED** [review]
LGTM

**Comment by bbrto21** [comment]
@swift-kim please resolve conflicts

**Comment by swift-kim** [comment]
Rebased on master.

**Pull request merged**
