### PR TITLE
Optimize for Windows

### PR DESCRIPTION
**Pull request by swift-kim**
- Avoid the use of `shell=True` for slightly better performance on Windows
- Do not create a symbolic link to `template_manifest.json` but permanently copy the file to fix a file deletion error on Windows

### CODE REVIEW

**Comment by swift-kim** [comment]
flutter-tizen commands are typically slower on Windows than on Linux mainly because:

- `git` is slow (especially `git rev-parse`)
- `subprocess.run` is slow
- `sdb` is slow

**Comment by HakkyuKim** [comment]
LGTM!

On a slightly different note, it seems that administrator privilege is needed on Windows for executing `createSync()` in `create.dart` line 182 (reference to the issue: https://docs.python.org/3/library/os.html#os.symlink). Should we inform the user with a simple message when the `create` command fails due to this issue? The tool currently prints out a block of stack trace in the console:

```
FileSystemException: Cannot create link, path = 'C:\Users\hakkyu.kim\mydir\project\flutter\flutter-tizen\flutter\packages\flutter_tools\templates\app\tizen.tmpl' (OS Error: A required privilege is not held by the client.
, errno = 1314)
#0      _Link.throwIfError (dart:io/link.dart:276:7)
#1      _Link.createSync (dart:io/link.dart:197:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:22:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:22:16)
#4      TizenCreateCommand.runCommand (package:flutter_tizen/commands/create.dart:176:17)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:972:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:831:33)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _runZoned (dart:async/zone.dart:1630:10)
#12     runZoned (dart:async/zone.dart:1550:10)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:820:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _runZoned (dart:async/zone.dart:1630:10)
#22     runZoned (dart:async/zone.dart:1550:10)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:281:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:223:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:230:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _runZoned (dart:async/zone.dart:1630:10)
#33     runZonedGuarded (dart:async/zone.dart:1618:12)
#34     runZoned (dart:async/zone.dart:1547:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#36     run.<anonymous closure> (package:flutter_tools/runner.dart)
#37     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#38     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#40     _rootRun (dart:async/zone.dart:1190:13)
#41     _CustomZone.run (dart:async/zone.dart:1093:19)
#42     _runZoned (dart:async/zone.dart:1630:10)
#43     runZoned (dart:async/zone.dart:1550:10)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#45     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#46     run (package:flutter_tools/runner.dart:46:10)
#47     main (package:flutter_tizen/executable.dart:57:9)
#48     main (file:///C:/Users/hakkyu.kim/mydir/project/flutter/flutter-tizen/bin/flutter_tizen.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Review by HakkyuKim — APPROVED** [review]

**Comment by swift-kim** [comment]
@HakkyuKim Requesting administrator privilege should be avoided whenever possible. If the code doesn't work properly on your machine, it still needs some more fix. (According to the link you attached, the current code did work on my machine maybe because Developer Mode was enabled.)

**Comment by swift-kim** [comment]
Symlinks are not supported on Windows (in user mode) so the entire directories are copied now. Please review the change.

@HakkyuKim

**Comment by HakkyuKim** [comment]
@swift-kim 
Checked that `flutter-tizen create` runs well without issues in Windows user mode.
LGTM!

**Pull request merged**
