### PR TITLE
Support native debugging

### PR DESCRIPTION
**Pull request by swift-kim**
Replaces the previous PR https://github.com/flutter-tizen/flutter-tizen/pull/312. Resolves https://github.com/flutter-tizen/plugins/issues/295.

Adds the `flutter-tizen-gdb` script for native debugging support. The script by default starts `gdbserver` on a connected device and waits for user input to perform additional operations.

Example:
```sh
$ cd my_app
$ sdb root off
$ sdb shell app_launcher -k com.example.my_app
$ sdb shell app_launcher -e com.example.my_app
$ flutter-tizen-gdb
pkg api_version: 4.0
Attached; pid = 6115
Listening on port 37375

Available commands:

r Run GDB client
p Print launch.json configuration
v Open this project in VS Code
q Quit

For detailed usage, see: https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-app's-native-code

Enter a command:
```

Entering `r` will directly launch GDB client from the command line (this was not possible with Dart in the previous PR). You can also press `p` and copy-paste the debug configuration to debug the app in VS Code. The detailed usage will be updated on [the wiki](https://github.com/flutter-tizen/flutter-tizen/wiki/Debugging-app's-native-code).

Somes parts of the script were derived from the flutter-tizen tool (such as the `TizenDevice` class and `locate_tizen_sdk`).

To run on a Windows host (not officially supported), you can use

```sh
python3 [path to flutter-tizen-gdb]
```

### CODE REVIEW

**Comment by swift-kim** [comment]
@haesik @bbrto21 @WonyoungChoi @HakkyuKim Any thoughts regarding the design of the tool?

**Comment by WonyoungChoi** [comment]
@swift-kim is it impossible to attach to a process executed with the `flutter-tizen run`?
I want the procedure to attach to be easier.

**Comment by swift-kim** [comment]
@WonyoungChoi It is possible if we replace `'-s'` in the following line with `'-e'`.

https://github.com/flutter-tizen/flutter-tizen/blob/e443d18999794b04f88b203ba8977152fd4999eb/lib/tizen_device.dart#L426

However I didn't make the change to avoid any confusion (I didn't want to explain two different ways to start an app in the wiki since I wanted to keep the document as simple as possible).

**Comment by WonyoungChoi** [comment]
@swift-kim  How about using `-e` in debug mode? I think it's understandable to use standalone launch in debug mode.

**Comment by swift-kim** [comment]
@WonyoungChoi Okay, I'll talk to you offline.

**Review by WonyoungChoi — APPROVED** [review]
Thanks for your hard work! LGTM 👍

**Pull request merged**
