### PR TITLE
Set FLUTTER_BUILD_DIR environment variable when building plugins

### PR DESCRIPTION
**Pull request by swift-kim**
Set the `FLUTTER_BUILD_DIR` environment variable during plugin and app build to allow some files to be downloaded to the location when building FlutterFire plugins.

cc @daeyeon @hs0225

### CODE REVIEW

**Comment by daeyeon** [comment]
Thanks a lot. I will check if it works well for our case.

**Comment by daeyeon** [comment]
Observed two issues below.

1) `FLUTTER_BUILD_DIR` is not passed as an environment variable when building apps with `project_def.prop`.

```make
# project_def.prop
USER_INC_DIRS = inc src ${FLUTTER_BUILD_DIR}/.firebaseSDK
```

```console
"/home/daeyeon/tizen-studio/tools/smart-build-interface/../llvm-10/bin/clang++" -c "src/cloud_functions_plugin.cc" -o "Debug/src/cloud_functions_plugin.o" -DTIZEN_DEPRECATION -DDEPRECATION_WARNING -DMOBILE_PROFILE
-DFLUTTER_PLUGIN_IMPL -DTIZEN -D__TIZEN__

-Iinc -Isrc -I/.firebaseSDK/inc  <-

-I"pch" -g3 -D_DEBUG -O0 -Wall -c
```

2) The value of `FLUTTER_BUILD_DIR` begins and ends with double quotes. This may look a bit unusual and cause unexpected behaviour when concatenating strings, so I tested it by removing the quotes them as shown below.

```bash
echo ${HOME}/.firebaseSDK
# /home/daeyeon/.firebaseSDK

echo ${FLUTTER_BUILD_DIR}
# "/home/daeyeon/code/sec.plugins/packages/firebase_tests/.dart_tool/flutter_build/aff5146beb803517879986d57df211ea"

echo ${FLUTTER_BUILD_DIR}/.firebaseSDK
# "/home/daeyeon/code/sec.plugins/packages/firebase_tests/.dart_tool/flutter_build/aff5146beb803517879986d57df211ea"/.firebaseSDK

echo ${FLUTTER_BUILD_DIR:1:-1}/.firebaseSDK
# /home/daeyeon/code/sec.plugins/packages/firebase_tests/.dart_tool/flutter_build/aff5146beb803517879986d57df211ea/.firebaseSDK
```

**Comment by swift-kim** [comment]
@daeyeon

> `FLUTTER_BUILD_DIR` is not passed as an environment variable when building apps with `project_def.prop`.

I think you need to use valid Makefile notation. Please refer to https://www.gnu.org/software/make/manual/make.html and try replacing the curly braces with parentheses.

> The value of `FLUTTER_BUILD_DIR` begins and ends with double quotes.

The directory path may contain spaces and you need to use double quotes to safely escape them. I'll remove the quotes from the variable value but you need to use them properly in your shell script.

**Comment by daeyeon** [comment]
There was a mistake in my previous observation. I don't know why, but both `${FLUTTER_BUILD_DIR}` and `$(FLUTTER_BUILD_DIR)` work. Sorry for confusing. I managed to build an app with `FLUTTER_BUILD_DIR`, but having trouble with a directory path that contains spaces. The following is observed when building an app in `/home/daeyeon/code/sec.plugins/packages/my test` on my machine.

```make
#project_def.prop
USER_INC_DIRS = inc src dep/include $(FLUTTER_BUILD_DIR)
```

```console
# build logs
...
 -I"/home/daeyeon/code/sec.plugins/packages/my -Itest/.dart_tool/flutter_build/8d81ef7ad3993e1f5b384e4f9fd8b91b" 
...
```
I attempted builds with enclosing the above `$(FLUTTER_BUILD_DIR)` in quotes, double quotes, and several forms of encapsulation, but the result is unchanged. Additionally, setting the include path or anything else through `USER_CPPFLAGS_MISC` doesn't seem to work at all. :thinking:

**Comment by daeyeon** [comment]
> I think you need to use valid Makefile notation. Please refer to https://www.gnu.org/software/make/manual/make.html and try replacing the curly braces with parentheses.

6.1 Basics of Variable References
To substitute a variable’s value, write a dollar sign followed by the name of the variable in parentheses or braces: **either ‘$(foo)’ or ‘${foo}’ is a valid reference to the variable foo.** This special significance of ‘$’ is why you must write ‘$$’ to have the effect of a single dollar sign in a file name or recipe.

**Comment by swift-kim** [comment]
@daeyeon 

> I attempted builds with enclosing the above `$(FLUTTER_BUILD_DIR)` in quotes, double quotes, and several forms of encapsulation, but the result is unchanged.

Tizen Studio supports [escaping spaces in `project_def.prop` files](https://github.sec.samsung.net/RS-TizenStudio/home/issues/201) using the `\` character as of Tizen Studio 4.5.

> Additionally, setting the include path or anything else through `USER_CPPFLAGS_MISC` doesn't seem to work at all.

As far as I know the `USER_CPPFLAGS_MISC` property in `project_def.prop` is [no longer supported](https://github.com/flutter-tizen/flutter-tizen/pull/493) by Tizen Studio. You could use the [`USER_CPP_OPTS` environment variable](https://github.com/flutter-tizen/flutter-tizen/blob/07c795b9a0634e983ce1fc68d4ccae88c24fc6da/lib/tizen_sdk.dart#L187) but make sure not to omit `-std=c++17` (which is mandatory for plugin build) when overriding the value.

**Comment by daeyeon** [comment]
Confirmed that my application was built successfully with https://github.com/flutter-tizen/flutter-tizen/pull/501/commits/b9b6279c846ff2139e71624be409126e7c5f351b. @swift-kim Can you let us know the minimum required SDK version for this feature once it's available? I believe the version needs to be specified in `pubspec.yaml`.

**Comment by swift-kim** [comment]
@daeyeon The flutter-tizen tool has no formal versioning policy, and actually [there is no way](https://github.com/flutter-tizen/flutter-tizen/issues/283) to specify its version in `pubspec.yaml`. The feature will be available (to those using the latest version of the tool) once this PR is merged.

**Review by daeyeon — APPROVED** [review]
this LGTM, but it would be good to get other folks chiming in as well.

**Review by daeyeon — APPROVED** [review]

**Pull request merged**
