### PR TITLE
Upgrade to Flutter 3.7

### PR DESCRIPTION
**Pull request by swift-kim**
- Update the framework and engine version to target Flutter 3.7.1.
- Update the embedder version to `a152671` (latest).
- Update the tool and package source code. See the commit history for details.

### CODE REVIEW

**Comment by JSUYA** [comment]
Release / pub ci error (https://github.com/flutter-tizen/flutter-tizen/actions/runs/4050192329/jobs/6967338701#step:5:113) is related to [this PR](https://github.com/flutter/flutter/pull/114103).

**Comment by JSUYA** [comment]
> Release / pub ci error (https://github.com/flutter-tizen/flutter-tizen/actions/runs/4050192329/jobs/6967338701#step:5:113) is related to [this PR](https://github.com/flutter/flutter/pull/114103).

@swift-kim 
I uploaded a [PR](https://github.com/swift-kim/flutter-tizen/pull/2) related to this issue to your 3.7 dev branch.
(I tested this by running the webview_flutter example)

**Comment by swift-kim** [comment]
Now this PR is ready for review and the engine repo's default branch is `flutter-3.7.1`.

**Comment by bbrto21** [comment]
I'm guessing you probably already know, In this version, when I run gallery on TM1 and TV emulator, hjorizontal listview icons  at the top of main page are not displayed properly.

**Review by bbrto21 — APPROVED** [review]
LGTM

**Review by JSUYA — APPROVED** [review]

**Pull request merged**
