### PR TITLE
Add Pause/Resume to ElmFlutterView

### PR DESCRIPTION
**Pull request by bbrto21**
Signed-off-by: Boram Bae <boram21.bae@samsung.com>

### CODE REVIEW

**Comment by swift-kim** [comment]
The user should also be able to "shutdown" the engine or "detach" it from the host view.

**Comment by bbrto21** [comment]
That's right, I'm already thinking about attach and detach. but I haven't been able to define the behavior of these myself yet.

**Comment by bbrto21** [comment]
> The user should also be able to "shutdown" the engine or "detach" it from the host view.

By the way, I try to make PR as small as possible :)

**Comment by JSUYA** [comment]
What about dependent on `SHOW` and `HIDE` events of `evas_object_`?
I think this can follow the policy of the application or uifw without a separate Pause and Resume setting.
(Of course I can't be sure that all evas_objects are `HIDE`d when the App is Paused)

**Comment by bbrto21** [comment]
> What about dependent on `SHOW` and `HIDE` events of `evas_object_`?

That's a good idea. If I understand you correctly, it seems that we have two options. 
And you seem to be talking about option 2. right?

1. Provide manual APIs (current PR).
2. Provide the view behaviors dependent on Event.

**Comment by JSUYA** [comment]
> > What about dependent on `SHOW` and `HIDE` events of `evas_object_`?
> 
> That's a good idea. If I understand you correctly, it seems that we have two options. And you seem to be talking about option 2. right?
> 
> 1. Provide manual APIs (current PR).
> 2. Provide behaviors of the view dependent on Event.

my opinion is 2. Um..
There may be a way to use window's EFL_APP_EVENT_RESUME and EFL_APP_EVENT_PAUSE.
(I did not check whether these events work well)

**Comment by bbrto21** [comment]
> The user should also be able to "shutdown" the engine or "detach" it from the host view.

@swift-kim
`shutdown engine` follows when the view is destroyed now. Is this enough?
I'm still investigating how to `detach` the `view` from the `host`(or `parent`). do you know anything about this?

**Comment by swift-kim** [comment]
> Is this enough?

Yes, I think we're handling it correctly. (Or do we need an explicit `Destroy` method?)

> do you know anything about this?

I don't have much idea but if there's no API for re-parenting a Elementary widget (table), there can only be a workaround for the problem at best.

**Comment by bbrto21** [comment]
the engine getter was added to ElmFlutterView(#421), therefore, it seems better to control the life cycle through the engine. so I close this draft.

**Pull request closed without merging**
